import os

def add_init_files(root_dirs):
    """
    遍历指定的根目录，为所有子目录（不包括 __pycache__）添加 __init__.py 文件。
    """
    for root_dir in root_dirs:
        if not os.path.isdir(root_dir):
            print(f"警告：目录 '{root_dir}' 不存在，已跳过。")
            continue

        for dirpath, dirnames, _ in os.walk(root_dir):
            # 排除 __pycache__ 目录
            if '__pycache__' in dirnames:
                dirnames.remove('__pycache__')

            init_file = os.path.join(dirpath, '__init__.py')
            if not os.path.exists(init_file):
                print(f"在 '{dirpath}' 中创建 __init__.py")
                with open(init_file, 'w') as f:
                    # 文件可以为空，也可以包含注释或初始化代码
                    f.write("# Automatically generated by add_init_files.py\n")

if __name__ == "__main__":
    # 指定需要处理的根目录列表
    # 我们将处理 src/ 和 config/ 目录
    target_directories = ['src', 'config']
    print("开始检查并添加 __init__.py 文件...")
    add_init_files(target_directories)
    print("\n处理完成。")